### ISSUE TITLE
API - E-Mail-Adresse bei Gruppen mit verlinkter Person

### ISSUE THREAD

**Issue by Michael-Schaer** [scout-ch/address-tool#6]
Wenn eine Gruppe eine Person als Kontakt einträgt, anstatt direkt eine E-Mail, so wird diese im nicht gefunden. Beispiel-Gruppe:
https://db.scout.ch/de/groups/1199

TODO:
 - Key "groups/0/email" auf leer überprüfen
 -> wenn leer auf Key "linked/people/0/email" zurückgreifen

**Comment by Vento-Nuenenen** [comment]
Ist gefixt mit 92d037f 

Mir ist aber aufgefallen, dass die letzte Zeile vom CSV verschluckt wird... Auch in der bestehenden version.

Zu Testen ist der Patch auf meinem System deployed.

**Comment by Michael-Schaer** [comment]
Tiptop, das klappt! Die letzte Zeile wird jetzt auch nicht mehr abgeschnitten (#8).

Jetzt bleibt nur noch, mal die Sarasani-Retouren durchzulassen und zu beobeachten, was da passiert :)
